name: page_view_360
description: A flutter package to utilize PageView.builder(). This package allow to implement a quad directional Pageview. User are allow to scroll/slide pages in 4 direction.
version: 0.0.3
homepage: 'https://github.com/saiful00000/page_view_360'

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
